/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Color: typeof import('./../components/color/index.vue')['default'];
    ProductCard: typeof import('./../components/product-card/index.vue')['default'];
    Result: typeof import('./../components/result/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TAlert: typeof import('tdesign-vue-next')['Alert'];
    TAside: typeof import('tdesign-vue-next')['Aside'];
    TAvatar: typeof import('tdesign-vue-next')['Avatar'];
    TAvatarGroup: typeof import('tdesign-vue-next')['AvatarGroup'];
    TBadge: typeof import('tdesign-vue-next')['Badge'];
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb'];
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem'];
    TButton: typeof import('tdesign-vue-next')['Button'];
    TCard: typeof import('tdesign-vue-next')['Card'];
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox'];
    TCol: typeof import('tdesign-vue-next')['Col'];
    TColorPickerPanel: typeof import('tdesign-vue-next')['ColorPickerPanel'];
    TContent: typeof import('tdesign-vue-next')['Content'];
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker'];
    TDateRangePicker: typeof import('tdesign-vue-next')['DateRangePicker'];
    TDialog: typeof import('tdesign-vue-next')['Dialog'];
    TDrawer: typeof import('tdesign-vue-next')['Drawer'];
    TDropdown: typeof import('tdesign-vue-next')['Dropdown'];
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem'];
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu'];
    TFooter: typeof import('tdesign-vue-next')['Footer'];
    TForm: typeof import('tdesign-vue-next')['Form'];
    TFormItem: typeof import('tdesign-vue-next')['FormItem'];
    THeader: typeof import('tdesign-vue-next')['Header'];
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu'];
    Thumbnail: typeof import('./../components/thumbnail/index.vue')['default'];
    TIcon: typeof import('tdesign-vue-next')['Icon'];
    TInput: typeof import('tdesign-vue-next')['Input'];
    TLayout: typeof import('tdesign-vue-next')['Layout'];
    TList: typeof import('tdesign-vue-next')['List'];
    TListItem: typeof import('tdesign-vue-next')['ListItem'];
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta'];
    TLoading: typeof import('tdesign-vue-next')['Loading'];
    TMenu: typeof import('tdesign-vue-next')['Menu'];
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem'];
    TOption: typeof import('tdesign-vue-next')['Option'];
    TPagination: typeof import('tdesign-vue-next')['Pagination'];
    TPopup: typeof import('tdesign-vue-next')['Popup'];
    TProgress: typeof import('tdesign-vue-next')['Progress'];
    TRadio: typeof import('tdesign-vue-next')['Radio'];
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton'];
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup'];
    Trend: typeof import('./../components/trend/index.vue')['default'];
    TRow: typeof import('tdesign-vue-next')['Row'];
    TSelect: typeof import('tdesign-vue-next')['Select'];
    TStepItem: typeof import('tdesign-vue-next')['StepItem'];
    TSteps: typeof import('tdesign-vue-next')['Steps'];
    TSubmenu: typeof import('tdesign-vue-next')['Submenu'];
    TSwitch: typeof import('tdesign-vue-next')['Switch'];
    TTable: typeof import('tdesign-vue-next')['Table'];
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel'];
    TTabs: typeof import('tdesign-vue-next')['Tabs'];
    TTag: typeof import('tdesign-vue-next')['Tag'];
    TTextarea: typeof import('tdesign-vue-next')['Textarea'];
    TTooltip: typeof import('tdesign-vue-next')['Tooltip'];
    TTree: typeof import('tdesign-vue-next')['Tree'];
    TUpload: typeof import('tdesign-vue-next')['Upload'];
  }
}
